### ISSUE TITLE
Restart not working

### ISSUE THREAD

**Issue by Lepefe** [MrOtherGuy/fx-autoconfig#1]
Hello Dev,
Thank you for your fxautoconfig. All my scripts are working fine.
But at **_Tools/userScripts_** the **_restart now!_** function is not working for me.
Cheers

**Comment by MrOtherGuy** [comment]
Well so it seems. I have pushed an update that fixes this.

After replacing boot.jsm with the new one you need to clear Firefox startup cache. The restart now! button should still do that even if it doesn't restart the browser so click that once and then close Firefox manually. Then after starting Firefox again the restart now! button should work again. But if it doesn't, then you would have to delete the startup cache files manually.
