### ISSUE TITLE
Extension Feedback

### ISSUE THREAD

**Issue by DenBoxed** [MrOtherGuy/fx-autoconfig#11]
I was wondering if you could test out my colorfultabs extension for bootstrap? It is still a tad buggy not sure what is missing at the current moment but would love some advice. 

https://github.com/DenBoxed/Colorfultabs/releases/tag/ctlrtabs  

Apologies in advance for making a topic that is not a real issue per say within in this sub. Still a tad new to using github's social options.

**Comment by MrOtherGuy** [comment]
Sorry, but I don't think I'd be of much value because I'm not really familiar at all with legacy extension system internals. At best I could answer stuff about how your extension interacts with my loader module, but based on a quick look at your source it doesn't look like it interacts with it at all - or am I mistaken?

I think your extension can't even be installed without some extra scripting to tell Firefox how to install legacy extensions - or am I mistaken there as well?

**Comment by DenBoxed** [comment]
I discovered you from this page https://github.com/dotiful/firefox-scripts, you are listed under userChrome.js. I figured most of you are testing old extensions my mistake.  You are not giving yourself enough credit, neat css section by the way. Also you are correct, It does require some extra scripting also Firefox Dev. 

If you ever get interested the setup process is pretty quick just a few downloads and file placements 

https://github.com/xiaoxiaoflood/firefox-scripts/blob/master/extensions/README.md
https://www.youtube.com/watch?v=_4fdUdp3G4o - Firefox: installing userChromeJS and legacy extensions 
https://github.com/xiaoxiaoflood/firefox-scripts

**Comment by MrOtherGuy** [comment]
I see. I'm pretty sure that you can't use the extension installation scripts by xiaoxiaoflood with my system. xiaoxioflood's loader is a much more full featured system than mine, and extension bootstrapping relies, at least partially, on the functionality provided by the loader script.

I don't feel our loaders are competing per se, but they are not compatible with each other.

How I see things is that code in their repository offers more or less full-featured package to install legacy extensions or use custom scripts or whatever. Whereas mine is more like a toolkit which just provides means to inject custom scripts in to Firefox and provides few helper functions that can be used by those scripts. In my view the two repositories exist for different use cases.

That being said. I don't personally use either loader in day-to-day browsing. I have a separate Firefox profile where my loader script is installed and just use it occasionally to test some things such as short custom scripts, and for that purpose my loader works better (and I get to test that it actually works).
