### ISSUE TITLE
Multi-line script descriptions?

### ISSUE THREAD

**Issue by aminomancer** [MrOtherGuy/fx-autoconfig#24]
I have some scripts with [pretty elaborate descriptions](https://github.com/aminomancer/uc.css.js/blob/master/JS/allTabsMenuExpansionPack.uc.js) that don't really fit on one line. Previously I've just used line endings to organize them, which works fine if you're just reading the code, but it means only the first line is matched by the regex. And now that I'm making this script manager, I want to show script descriptions (I'm basing the layout on about:addons), so I need another way to handle that.

First thing that came to mind is replacing all the line endings with some placeholder code point, so fx-autoconfig picks up the entire thing, and then the script manager can replace all of those code points with `\n`. But unfortunately that would make the description difficult to read in the actual script file. I've searched to see if there's a code point that text editors will display as a line break but regex will not consider a line break, but there doesn't seem to be one.

Do you have any ideas? I guess the match expression could be changed so that it captures everything up to the next `\n// @` but maybe that has some undesirable effects.

**Comment by MrOtherGuy** [comment]
Hmm, I think we could match description specifically against this:

```js
    this.description = headerText
      .match(/\/\/ @description\s+(.+?)\/\/ [@=]+/is)
      ?.[1].replace(/^\/\//gm,"");
```

I believe it would take everything up to `// @` or `// =`. Doing it like this would require you to to put a `// ` to the start of the each line of the description but I suppose that might be fine.

In a couple of tests I run it seems to work fine, but you might want to check if it works for more complicated input.

**Comment by aminomancer** [comment]
Nice! That seems to work well for the format I've been using. The only nitpick I can see is that it also matches the final linebreak before the next metadata field. But maybe best to just get rid of that with another `replace`

**Comment by MrOtherGuy** [comment]
Patch [f1bc35d](https://github.com/MrOtherGuy/fx-autoconfig/commit/f1bc35d6fc232341bf7568bafb3e86e2858b321e) should fix this. The matching regexp should now also remove the ending newline as well as possible white-space at beginning of each line.

**Comment by aminomancer** [comment]
Looks great, thanks!

**Comment by aminomancer** [comment]
Hey, would it make sense to change the regex so it doesn't eat extra spaces? I ended up adding a markdown parser so scripts can add rich descriptions with links etc., so you'd basically just write a markdown readme and then comment out every line. The one area where it differs is just that the description matcher returns the description but without leading whitespace, which markdown uses for nested lists.

![image](https://user-images.githubusercontent.com/33384265/210160752-b9521927-3f72-4431-8a96-1c2c270e16df.png)

^ I did a workaround for testing (basically `// ␠  lorem...` and then replace the `␠` in the frontend code) but then only my script manager handles that character correctly. Maybe just remove the first space character? `/^\/\/\s?/gm` Idk if that has any bad side effects, seems to work though

**Comment by MrOtherGuy** [comment]
> Maybe just remove the first space character?
 
I don't think I understand what you mean. We are already eating the leading space from each line in [description multi-line parsing](https://github.com/MrOtherGuy/fx-autoconfig/blob/a97d4b9d1eea3fca4779693704c6a4ee932ce55e/profile/chrome/utils/boot.jsm#L98) - so presumably you mean something else.

Another way to make multi-line description nicer would be to have another header, let's say `@long-description` which, if present makes the `@description` parsing look for a block-comment so the header would look like this:

```javascript
// ==UserScript==
// @name           test_utils
// @long-description
// @description
/*
....
*/
// ==/UserScript==
```

I mean, we *could* do this without the extra header, but I tried it before, and it gets pretty complex to try to match both normal-style and block-comments. It's just cleaner if the script itself informs that description is in block-comment form.

Or, we could just have a separate long-description field, but I think I would rather just have one description field.

Your `about:userchrome` looks pretty neat, good job there!

**Comment by aminomancer** [comment]
> > Maybe just remove the first space character?
> 
> I don't think I understand what you mean. We are already eating the leading space from each line in [description multi-line parsing](https://github.com/MrOtherGuy/fx-autoconfig/blob/a97d4b9d1eea3fca4779693704c6a4ee932ce55e/profile/chrome/utils/boot.jsm#L98) - so presumably you mean something else.

In `/^\/\/ */gm` the ` *` removes _all_ leading spaces, not just the first one. So if my description looks like
```
// 1. item 1
//    - sub-item 1
//    - sub-item 2
// 2. item 2
```
Then when calling `_ucUtils.getScriptData()`, the description property will be:
```
1. item 1
- sub-item 1
- sub-item 2
2. item 2
```
And then that will get parsed out by the markdown parser like this:

1. item 1
- sub-item 1
- sub-item 2
2. item 2

> 
> Another way to make multi-line description nicer would be to have another header, let's say `@long-description` which, if present makes the `@description` parsing look for a block-comment so the header would look like this:
> 
> ```js
> // ==UserScript==
> // @name           test_utils
> // @long-description
> // @description
> /*
> ....
> */
> // ==/UserScript==
> ```
> 
> I mean, we _could_ do this without the extra header, but I tried it before, and it gets pretty complex to try to match both normal-style and block-comments. It's just cleaner if the script itself informs that description is in block-comment form.
> 
> Or, we could just have a separate long-description field, but I think I would rather just have one description field.

That seems pretty good, it's definitely a lot more readable as plain text and should work equally well for the script manager.

> Your `about:userchrome` looks pretty neat, good job there!

Thanks! I'm adding syntax highlighting in code blocks now. Now we can put code within markdown within a description within a header within a script lol.

```
// @description
/*
~~~css
button {
  color: red;
}
~~~
*/
```

**Comment by MrOtherGuy** [comment]
Right, so I changed `@description` behavior in [this commit](https://github.com/MrOtherGuy/fx-autoconfig/commit/9c81a8691a995ef40e8ba91b073107bd6bfda563) to match what I described above. I feel it's kinda funny that `@long-description` is a separate "toggle" but this system should make the same header parse correctly (with fallback value) in other loaders too which don't support multi-line descriptions.

The only thing which will break it (well, I don't promise the *only* thing) is that you can't directly use `*/` sequences inside the description - because the script execution (not our metadata parser) treats it as normal javascript source file so it needs to be valid for that. And similarly if you forget to add the closing `*/` then the javascript engine treats the source as comment until it finds the next `*/`.

But yeah, if either of those happen then you are gonna notice on next startup so it's not a big deal I think.

**Comment by aminomancer** [comment]
Looks perfect! Thanks for the quick response. The new getScriptData changes look useful too
