### ISSUE TITLE
Bug in the script file regex

### ISSUE THREAD

**Issue by aminomancer** [MrOtherGuy/fx-autoconfig#25]
I noticed some files I marked `script.uc.js.disabled` were still showing up in fx-autoconfig, so did some testing. You can take a .exe file and change its name to `program.uc.js.exe` and it'll confuse fx-autoconfig. It's because of this expression:
```regex
/(.+\.uc\.js)|(.+\.sys\.mjs)$/i
```
The first capturing group doesn't have an end anchor, so although it'll exclude `module.sys.mjs.exe` it will still match `script.uc.js.exe`. Here are 2 possibilities, I probably screwed them up somehow but they seem to work correctly:
```regex
/(.+\.uc\.js|.+\.sys\.mjs)$/i
```
```regex
/(.+\.uc\.js)$|(.+\.sys\.mjs)$/i
```

**Comment by MrOtherGuy** [comment]
Ugh, nice catch - friggin regexp, you always mess something up.

I went with `/(.+\.uc\.js|.+\.sys\.mjs)$/i` and then created bunch of bogus test scripts in [93a10c0](https://github.com/MrOtherGuy/fx-autoconfig/commit/93a10c0721496f881277e6c36e8e433abd8a25c7) with names that are supposed to be invalid. It does indeed look like the manager correctly ignores them now.
