### ISSUE TITLE
fs.jsm location? [DOCUMENTATION]

### ISSUE THREAD

**Issue by aranapatona** [MrOtherGuy/fx-autoconfig#29]
Documentation states 2 files should be in the ./Utils directory, boot.jsm, and chrome.manifest,
is this third file fs.jsm (filesystem??) needed ? or was just  for dev purposes?

**Comment by MrOtherGuy** [comment]
Good call, the documentation needs to be updated to mention fs.jsm.

And yes, you need it and it needs to saved to the same directory where boot.jsm is.

**Comment by MrOtherGuy** [comment]
This is fixed with https://github.com/MrOtherGuy/fx-autoconfig/commit/77182db9608655a4848b5082831e430c3e34e208
