### ISSUE TITLE
Cannot access Thunderbird DOM elements inside html in TB 115

### ISSUE THREAD

**Issue by Frank-Steiner** [MrOtherGuy/fx-autoconfig#35]
Hi,
I tried to add [Aboutconfig-button.uc.js](https://github.com/Endor8/userChrome.js/blob/master/Thunderbird/Thunderbird%20-%20Release%20115/Aboutconfig-button.uc.js) to Thunderbird 115 after upgrading to the new version of fx-autoconfig.
My changes in userChrome.au.css all still work fine, so there is no general problem with Tb 115. 

However, the Aboutconfig-button.uc.js fails because `document.getElementById('unifiedToolbarContent');` will return null instead of the DOM object.

I figured out that this happens with alle elements that are inside a html element. The unifiedToolbarContent (which is the element that contains the buttons like GetMsg, Write etc.) is defined as
```<html:ul id="unifiedToolbarContent" ...```

When I try e.g. the
```<menubar id="toolbar-menubar"...```
I get the element with the getElementById. The null is only returned for elements inside `<html:...`. It does work with the [Endor8 loader](https://github.com/Endor8/userChrome.js/tree/master/Thunderbird/userChrome), so it must be possible somehow. But I'm not skilled enough to see in which way the scripts are loaded in different ways in Endor8 and fx-autoconfig, so I hope you might have an idea.

As TB developers seems to be aiming to change lots of elements to html objects, it would be very bad if those could not be used with scripts in fx-autoconfig.

I didn't change anything in fx-autoconfig but the code in userChrome.au.css, everything else just copied 1:1.

Let me know if I can provide further information or test something to help!
Thanks a lot!
cu,
Frank

**Comment by MrOtherGuy** [comment]
`document.getElementById();` should return html elements just fine, but one thing that might be happening is that this `unifiedToolbarContent` button doesn't exist *yet* at the time you script is being run. Perhaps the other loader executes scripts later.

So, if that's what's happening then perhaps it is enough to just wait for startup to finish - which you could do for example like this:

```js
_ucUtils.startupFinished()
.then(function(){
  if (location != 'chrome://messenger/content/messenger.xhtml') return;
 // ...
 position.parentNode.insertBefore(toolbarbutton, position.nextSibling);
})
.catch(console.error)
```

**Comment by MrOtherGuy** [comment]
I was able to find what's going wrong. Indeed the `unifiedToolbarContent` button doesn't exist immediately on startup so you need to wait for window being ready - for example by using `_ucUtils.startupFinished()`.

However, it seems Thunderbird team has made some nice changes that align it more closely to Firefox startup, so if you tried to use `_ucUtils.startupFinished()` on TB 115, it would just never resolve.

I fixed that and couple of other TB 115 issues in [e6cca44](https://github.com/MrOtherGuy/fx-autoconfig/commit/e6cca44a5881c2df65b9897132dcedf154fd5d7e) so now it should work nicely in TB 115.

That being done, support for old TB 102 (just like Firefox 102) is now removed.

Please check if you can now run your script (again, by waiting for `_ucUtils.startupFinished()` ) and that no other issues manifest.

**Comment by Frank-Steiner** [comment]
Yes, with the new patch and the startupFinished function it works as expected! Many thanks!!

**Comment by MrOtherGuy** [comment]
Cool!
Just a heads up there was a startup issue which broke the loader completely if either JS or CSS directory didn't exist. If you created them both, then no issues - but now it should work even if one of them is missing.
