### ISSUE TITLE
Better startup cache deletion method for user

### ISSUE THREAD

**Issue by wdkevonfernando** [MrOtherGuy/fx-autoconfig#4]
It is possible to delete the startup cache from the "about:support" page using the "clear startup cache..."-button. 
So instead of asking the user to delete the startup cache manually, it would be more comfortable and maybe even safer to delete it that way. It would be nice if the instructions would be updated to use the browser given option.

**Comment by MrOtherGuy** [comment]
Thanks! Yeah, it definitely sounds I should do that. I think I'll keep the manual deletion method documented as backup, but I'll add a new section that instructs to use about:support.
