### ISSUE TITLE
getBoolPref unexpected error

### ISSUE THREAD

**Issue by Laurens256** [MrOtherGuy/fx-autoconfig#41]
When using the writeFile function, something called getBoolPref gets called inside fs.sys.mjs (line 170). This results in the following error:

```
Uncaught (in promise) NS_ERROR_UNEXPECTED: Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsIPrefBranch.getBoolPref]
```

Enabling allowUnsafeWrites pref fixes this, but the file I passed to the writeFile function is inside my resources directory so this shouldn't be necessary. Removing this line and the if statement which checks for allowUnsafeWrites also fixes this code and everything works as expected. Problem is (I think) something with getBoolPref.

Thanks for the great product btw :)

**Comment by Laurens256** [comment]
I found the problem was my `about:config` did not have a `userChromeJS.allowUnsafeWrites` key at all. Setting this key to either true or false fixed the issue. Might have been a mistake on my part, feel free to close if it was :)

**Comment by MrOtherGuy** [comment]
Thanks for reporting. This is definitely oversight on my part - it should not fail if the pref is missing. c8d08a8 should fix that.

**Comment by Laurens256** [comment]
Thanks, this fixed it
