### ISSUE TITLE
Assign same function to multiple hotkeys

### ISSUE THREAD

**Issue by raziel6868** [MrOtherGuy/fx-autoconfig#53]
I want both Ctrl + L and Ctrl + E to focus on the URL bar when pressed so here's my attempt:
```
SessionStore.promiseInitialized.then(() => {
  document.getElementById("focusURLBar").setAttribute("key", "E");
  document.getElementById("key_search2").setAttribute("modifiers", "accel,shift");
});
```
While this code does map the function of Ctrl + L to Ctrl + E, it also disables the Ctrl + L shortcut. I'm looking for a way to keep Ctrl + L functioning as is, while also setting Ctrl + E as a new shortcut for the same function.

**Comment by MrOtherGuy** [comment]
There's couple of ways you could achieve that, but I think the most sane would be to create a copy of that focusURLBar `<key>` element and change the `key` attribute of the copy. (And you'll probably want to change it's id attribute as well.)

**Comment by raziel6868** [comment]
I've tried creating a new <key> element and clone <key> element but none of them worked. I think _ucUtils.registerHotkey is the way but I don't know how to use it.
My browser is Floorp 11.14.0 (Firefox ESR 115).
```
SessionStore.promiseInitialized.then(() => {
  let mainKeyset = document.getElementById("mainKeyset");
  let newKey = document.createElement("key");
  newKey.setAttribute("id", "focusURLBar_E");
  newKey.setAttribute("data-l10n-id", "location-open-shortcut");
  newKey.setAttribute("command", "Browser:OpenLocation");
  newKey.setAttribute("modifiers", "accel");
  newKey.setAttribute("key", "E");
  mainKeyset.appendChild(newKey);
  document.getElementById("key_search2").setAttribute("modifiers", "accel,shift");
});
```
```
SessionStore.promiseInitialized.then(() => {
  let originalKey = document.getElementById("focusURLBar");
  let newKey = originalKey.cloneNode(true);
  newKey.setAttribute("id", "focusURLBar_E");
  newKey.setAttribute("key", "E");
  originalKey.parentNode.appendChild(newKey);
  document.getElementById("key_search2").setAttribute("modifiers", "accel,shift");
});
```

**Comment by MrOtherGuy** [comment]
How did you solve this if you don't mind me asking? I had time to briefly look at this and there was definitely some weird unexpected behavior involved regarding the key element that was created.

**Comment by raziel6868** [comment]
I duplicates focusURLBar <key> element, changes its id and key value, and appends it under the 'mainKeyset', then do the same as my old code
```
SessionStore.promiseInitialized.then(() => {
  let clone = document.getElementById('focusURLBar').cloneNode(true);
  clone.id = "key_focusURLBar";
  document.getElementById('mainKeyset').appendChild(clone);
  document.getElementById("focusURLBar").setAttribute("key", "E");
  document.getElementById("key_search2").setAttribute("modifiers", "accel,shift");
});
```
Here are the results observed with the Remote Debugger:
Before the code was executed:
```
<key xmlns="http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul">
  <keyset id="keyset">
    <key id="focusURLBar" data-l10n-id="location-open-shortcut" command="Browser:OpenLocation" modifiers="accel" key="L" />
  </keyset>
</key>
```
After the code execution:
```
<key xmlns="http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul">
  <keyset id="keyset">
    <key id="focusURLBar" data-l10n-id="location-open-shortcut" command="Browser:OpenLocation" modifiers="accel" key="E" />
    <key id="key_focusURLBar" data-l10n-id="location-open-shortcut" command="Browser:OpenLocation" modifiers="accel" key="L" />
  </keyset>
</key>
```

**Comment by raziel6868** [comment]
> There's couple of ways you could achieve that, but I think the most sane would be to create a copy of that focusURLBar `<key>` element and change the `key` attribute of the copy. (And you'll probably want to change it's id attribute as well.)
@MrOtherGuy Thank you for your idea about creating a copy of that focusURLBar key element. It was exceptionally helpful

**Comment by MrOtherGuy** [comment]
Alright, cool - that works like I would expect. Good job!
