### ISSUE TITLE
Question about _ucUtils.windows.get(onlyBrowsers)

### ISSUE THREAD

**Issue by Mitezuss** [MrOtherGuy/fx-autoconfig#7]
You said:
_Return a list of handles for each window for this firefox instance. If onlyBrowsers is false then this only includes browser windows (not consoles or similar). onlyBrowsers defaults to true._

And:

`let windows = Services.wm.getEnumerator(onlyBrowsers ? 'navigator:browser' : null);`

So, if onlyBrowsers is false, null is "only browser windows"  ?

regards

**Comment by MrOtherGuy** [comment]
I think the readme is wrong. It looks like it should say something like "If onlyBrowsers is true then this only includes browser windows, if it's false then it also includes consoles, PiP, non-native notifications etc."

**Comment by Mitezuss** [comment]
@MrOtherGuy 

Yes i think so too.

**Comment by MrOtherGuy** [comment]
I've modified the readme to correct the description. Thanks for letting me know!
