### ISSUE TITLE
A question, about chrome.manifest

### ISSUE THREAD

**Issue by Mitezuss** [MrOtherGuy/fx-autoconfig#9]
Hi, i wanna know what is the diferent beetwen, for example:

content res ../res/
and
resource userchome ../res/

So,
chrome://res/content/
resource://userchome/

You are not using "resource", just "content" both style and script; so, when i should use resource ?

Thanks

**Comment by MrOtherGuy** [comment]
[Here's something about chrome manifests](https://firefox-source-docs.mozilla.org/build/buildsystem/chrome-registration.html)

In addition, there are some cases (though I can't give you an example of the top of my head) where the program logic gives different permissions to resources based on their uri. Some features may only be available in resources loaded from chrome:// uri for example.

**Comment by Mitezuss** [comment]
Thanks
